"""IELTS-specific prompts for all agent types."""

from .ielts_prompts import (
    TUTOR_SYSTEM_PROMPT,
    PRACTICE_SYSTEM_PROMPT,
    SCORING_SYSTEM_PROMPT,
    WRITING_BAND_DESCRIPTORS,
    SPEAKING_BAND_DESCRIPTORS,
)

__all__ = [
    "TUTOR_SYSTEM_PROMPT",
    "PRACTICE_SYSTEM_PROMPT",
    "SCORING_SYSTEM_PROMPT",
    "WRITING_BAND_DESCRIPTORS",
    "SPEAKING_BAND_DESCRIPTORS",
]
